CREATE DATABASE CARS;
USE CARS;
-- READ DATA --
SELECT * FROM CAR_DEKHO;
-- TOTAL CARS TO GET A COUNT OF TOTAL RECORDS --
SELECT COUNT(*) FROM CAR_DEKHO;
-- THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS WILL BE AVILABLE IN 2023? --
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2023;
-- THE MANAGER ASKED THE EMPLOYEE HOW MANY CARS IS AVAILABLE IN 2020,2021,2022 --
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2020; -- 74
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2021; -- 7
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2022; -- 7
-- GROUP BY -- 

SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR IN (2020,2021,2022) GROUP BY YEAR;
-- CLIENT ASKED ME TO PRINT THE TOTAL OF ALL CARS BY YEAR. I DONT SEE ALL THE DETAILS --
SELECT YEAR,COUNT(*) FROM CAR_DEKHO GROUP BY YEAR;
-- CLIENT ASKED TO CAR DEALER AGENT HOW MANY DIESEL CARS WILL THERE BE IN 2020? --
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2020 AND FUEL = "DIESEL";
-- CLIENT REQUESTED A CAR DEALER AGENT HOW MANY PETROL CARS WILL THERE BE IN 2020? --
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2020 AND FUEL = "PETROL";
-- THE MANAGER TOLD THE EMPLOYEE TO GIVE A PRINT ALL THE FUEL CARS (PETROL,DIESEL AND CNG) COME BY ALL YEAR --
SELECT YEAR,COUNT(*) FROM CAR_DEKHO WHERE FUEL = "PETROL" GROUP BY YEAR;
SELECT YEAR,COUNT(*) FROM CAR_DEKHO WHERE FUEL = "DIESEL" GROUP BY YEAR;
SELECT YEAR,COUNT(*) FROM CAR_DEKHO WHERE FUEL = "CNG" GROUP BY YEAR;
-- MANAGER SAID THERE WERE MORE THAN 100 CARS IN A GIVEN YEAR, WHICH YEAR HAD MORE THAN 100 CARS? --
SELECT YEAR,COUNT(*) FROM CAR_DEKHO GROUP BY YEAR HAVING count(*)>100;
SELECT YEAR,COUNT(*) FROM CAR_DEKHO GROUP BY YEAR HAVING count(*)<100;
-- THE MANAGER SAID TO THE EMPLOYEE ALL CARS COUNT DETAILS BETWEEN 2015 AND 2023; WE NEED A COMPLETE LIST --
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR BETWEEN 2015 AND 2023;
-- THE MANAGER SAID TO THE EMPLOYEE ALL CAR DETAILS BETWEEN 2015 TO 2023 , WE NEED COMPLETE LIST --
SELECT * FROM CAR_DEKHO WHERE YEAR BETWEEN 2015 AND 2023;